name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Build and Push Frontend Image"]
    types:
      - completed

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            cd ~/academix

            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.production
            echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" > .env.production

            docker pull ${{ secrets.DOCKER_USERNAME }}/academix-frontend:latest

            # SOLUCION AL BUG DE DOCKER-COMPOSE
            docker-compose stop frontend || true
            docker-compose rm -f frontend || true

            docker-compose up -d --no-deps frontend